logger:
        project: "kaori/AISeed" # replace with your own
        api_key: YOUR API KEY # replace with your own
        tags: None
        log_params: true
architect_settings:
        is_full: false
        is_pretrained: true
        is_freeze: false
dataset_settings:
        name: CIFAR10
        path: data/CIFAR10
        n_cls: 10
        num_workers: 0
        batch_size: 16
training_settings: 
        gpu_ids: [0]
        loss: ce
        metrics: [accuracy, 'F1']
        ckpt_path: "./models/test"
        max_epochs: 5
        optimizer: adam
        lr_scheduler: step
        lr: 0.0001
        early_stopping: false
        monitor: "train_loss"
        mode: 'min'
        