logger:
        project: "kaori/AISeed" # replace with your own
        api_key: YOUR API KEY # replace with your own
        tags: None
        log_params: true
architect_settings:
        is_full: false
        is_freeze: false
dataset_settings:
        name: CIFAR10
        path: data/PennFudanPed
        n_cls: 2
        num_workers: 0
        batch_size: 8
training_settings: 
        gpu_ids: [0]
        loss: none
        metrics: [map]
        ckpt_path: "./models/test_faster_rcnn"
        max_epochs: 10
        optimizer: adam
        lr_scheduler: step
        lr: 0.0001
        early_stopping: false
        monitor: "train_loss"
        mode: 'min'
        